# @file ekf.yaml
# @brief ROS2 EKF parameters - fusion of GPS and IMU for pose estimation
# @cite https://docs.ros.org/en/lunar/api/robot_localization/html/_downloads/robot_localization_ias13_revised.pdf

frequency: 30.0
sensor_timeout: 0.1
two_d_mode: true

# Frames
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map  # 'odom' if you're fusing only IMU/odom

# IMU Input
imu0: /imu/data
imu0_config: [false, false, false,  # x y z pos
              true, true, true,     # roll pitch yaw
              false, false, false,  # vx vy vz
              true, true, true,     # roll_vel pitch_vel yaw_vel
              false, false, false]  # ax ay az

# GPS Input
gps0: /gps/filtered
gps0_config: [true, true, true,     # x y z pos
              false, false, false,  # roll pitch yaw
              false, false, false,  # velocity
              false, false, false,  # angular velocity
              false, false, false]  # accel

use_control_input: false
