# @file navsat_config.yaml
# @brief Transforms GPS lat/lon to cartesian meters.

frequency: 10
delay: 0.0

magnetic_declination_radians: 0.0
yaw_offset: 0.0
zero_altitude: false
broadcast_utm_transform: false
publish_filtered_gps: false

use_odometry_yaw: false
use_local_cartesian: true
